### ISSUE TITLE
Using jest-runner-eslint will omit running tests

### ISSUE THREAD

**Issue by saptaru** [jest-community/jest-runner-eslint#101]
Hi,

I have the following jest config:
```
{
    "verbose": true,
    "roots": [
      "./src",
      "./test"
    ],
    "collectCoverage": false,
    "collectCoverageFrom": [
      "src/**/*.js",
      "!**/node_modules/**"
    ],
    "coverageReporters": [
      "html"
    ],
    "displayName": "lint",
    "runner": "jest-runner-eslint",
    "testMatch": [
      "<rootDir>/**/*.js"
    ],
    "watchPlugins": [
      "jest-runner-eslint/watch-fix"
    ]
  }
```

Everytime the test will run it displays only the number of passed test suites but not loading the unit tests.
I have put a test which will intentionally fail and tests are still passing; but if I remove the jest-runner-eslint it will run correctly and it will pass.

I am using the following packages versions:
"jest": "26.4.2",
"jest-runner-eslint": "0.10.0",
"eslint": "7.8.1",
"babel-eslint": "10.1.0",
"babel-loader": "8.1.0",

I have another project which is using jest projects and have setup the jest-runner-eslint inside the jest project configuration file but had the same result as above.

Any idea why is this happening?

Thank you!

**Comment by ljharb** [comment]
Because you're trying to use the eslint runner for tests :-) you have to use multiple *projects* in jest, one for eslint, one for tests.

**Comment by saptaru** [comment]
Thanks!
That did the trick.
