### ISSUE TITLE
Using jest-runner-eslint to lint .vue files

### ISSUE THREAD

**Issue by saptaru** [jest-community/jest-runner-eslint#102]
Just wandering if it is possible to scan .vue files using jest-runner-eslint.
My setup is the following:
**in my package.json:**
```
{
jest-runner-eslint": {
    "cliOptions": {
      "ext": [
        ".vue",
        ".js"
      ]
    }
  }
}
```
**in jest.config.js:**
```
module.exports = {
    verbose             : true,
    rootDir             : './',
    moduleNameMapper    : {
        '^vue$': 'vue/dist/vue.common.js'
    },
    moduleFileExtensions: [
        'js',
        'vue',
        'jsx',
        'json',
        'ts',
        'tsx'
    ],
    collectCoverage     : false,
    collectCoverageFrom : [
        'src/**/*.{js,vue}',
        '!**/node_modules/**'
    ],
    coverageReporters   : [
        'lcov',
        'html',
        'text-summary'
    ],
    reporters           : [
        'default',
        [
            'jest-sonar',
            {
                outputDirectory: 'coverage',
                outputName     : 'sonar-reporter.xml'
            }
        ]
    ],
    watchPlugins        : ['jest-runner-eslint/watch-fix'],
    projects            : [
        {
            displayName: 'Test',
            transform  : {
                '^.+\\.js$'  : 'babel-jest',
                '.*\\.(vue)$': 'vue-jest'
            }
        },
        {
            runner     : 'jest-runner-eslint',
            displayName: 'Lint',
            testMatch  : [
                '<rootDir>/src/**/*.vue',
                '<rootDir>/src/**/*.js',
                '<rootDir>/test/**/*.js'
            ]
        }
    ]
};
```

if I run npx jest it will only scan .js files.
My decoupled npm script "npm run lint" runs ok if I pass the --ext "eslint --ext .js,.vue ./src ./test", but I would like to make it work with jest-runner-eslint if possible.

Thank you!

**Comment by cameron-martin** [comment]
If you specify [`moduleFileExtensions`](https://jestjs.io/docs/en/configuration#modulefileextensions-arraystring) to include `vue` then this will work.

**Comment by saptaru** [comment]
I am doing this already in my jest config. It doesn't work.

`module.exports = {
...
moduleFileExtensions: [
        'js',
        'vue',
        'jsx',
        'json',
        'ts',
        'tsx'
    ],
...
`

**Comment by cameron-martin** [comment]
You need to specify that in your project config, rather than your global config. The distinction between the two things isn't made clear in the docs, but can be seen in the [type definitions](https://github.com/facebook/jest/blob/5da90b58eb6673e6f406f9ebc369b1f0fb747384/packages/jest-types/src/Config.ts#L247-L370). I think any project config specified at the global level when using projects is ignored, and vice versa.
