### ISSUE TITLE
Use ESLint class instead of CLIEngine if available

### ISSUE THREAD

**Issue by lencioni** [jest-community/jest-runner-eslint#119]
CLIEngine is deprecated in v7 https://eslint.org/docs/developer-guide/nodejs-api#cliengine and the ESLint class is the new node API. https://eslint.org/docs/developer-guide/nodejs-api#eslint-class

jest-runner-eslint should detect if ESLint is available, and use that instead of CLIEngine.

**Comment by SimenB** [comment]
Never noticed this issue - this was fixed in #128
