### ISSUE TITLE
Classes invoked without `new`?

### ISSUE THREAD

**Issue by kesne** [jest-community/jest-runner-eslint#17]
I'm trying to use this runner in my project and running into an issue where the test framework is invoked without `new`. It looks like the module exports a class, but gets invoked like a function. Relevant part of Jest:
https://github.com/facebook/jest/blob/master/packages/jest-runner/src/run_test.js#L100

**Comment by kesne** [comment]
Turns out `runner` and `testRunner` are different 😅

**Comment by alexlrobertson** [comment]
Mind sharing the difference? I'm trying to figure out how to configure `jest` to run both my tests and linting using CLI arguments.
