### ISSUE TITLE
How to configure this in a monorepo?

### ISSUE THREAD

**Issue by sgwilym** [jest-community/jest-runner-eslint#18]
I'd like to use this to run our tests, but we have a few deviations from the norm that have made us unable to use this runner.

- We have a monorepo and run tests against multiple packages in parallel using Jest's `projects` config
- Each of these projects has its own Jest config
- Our eslint config is also a package in this monorepo

This seems to cause a lot of subtle problems given that many dependencies are spread across many different locations, and this combined with there not being a lot of feedback on whether the configuration is respected or not, I was wondering how or if this kind of structure can be catered to with this runner.

Thanks!

**Comment by sgwilym** [comment]
Okay, finally figured this out! This issue stemmed from my _erroneous impression that this runner linted in addition to running tests normally_ -- but once I eventually figured out that this runner is only responsible for linting, then this was just a matter of creating a new jest config at the root level that looked a bit like this: 

```
module.exports = {
  name: "monorepo-lint",
  displayName: "lint",
  runner: "jest-runner-eslint",
  testResultsProcessor: "jest-teamcity",
  testRegex: "packages/.*.js$",
};
```

Then I added this new config to the array of projects in the Jest config, and bam.

**Comment by rogeliog** [comment]
Hey!

Thanks for posting the solution, I really appreciate it
