### ISSUE TITLE
Parser option ignored in eslint config.

### ISSUE THREAD

**Issue by moimael** [jest-community/jest-runner-eslint#19]
Hi,

I converted our project to use the jest eslint test runner instead of eslint directly but have a weird issue. 

Using eslint with `parser` set to `babel-eslint` in the config file worked perfectly, but when using the jest-runner, It doesn't seems to pick it up (I get unexpected token issues, but the rest of the config works).

If I override the `parser` in `cliOptions` then it works but it should take the one from my `.eslintrc.js` in the first place.

Thanks !

**Comment by alexlrobertson** [comment]
I'm encountering the same issue and also with my rules. None of my rules seem to be in effect.

**Comment by rogeliog** [comment]
Hi! Thanks for reporting and sorry for the late response, I've been sick

That is an interesting point... @alexlrobertson @moimael does it take into account any of the eslintrc options? @alexlrobertson What happens after you set the `cliOptions`?

**Comment by marcins** [comment]
I've worked out why this happens, the parser specified in `cliOptions` passed to the `CLIEngine` is applied to the config at the end - overriding anything read from `eslintrc` files.

https://github.com/eslint/eslint/blob/cbf0fb9b209dd2d3efe69510925805da5fa8e29f/lib/config.js#L349-L354

Espree is being set as the default parser in `normalizeConfig` if one isn't passed in the `jest-runner-eslint` config:

https://github.com/jest-community/jest-runner-eslint/blob/2e2b65ef7bf698e501d6e175a210fd7f7b6bbffc/src/utils/normalizeConfig.js#L49-L51

Removing setting a default parser in `normalizeConfig` fixes the issue, but I'm not sure of your intention in providing that as a default so not sure that just removing this is the right fix - in my testing the internal default options for eslint have espree as the parser, so if one is not specified this is what will be applied.

**Comment by moimael** [comment]
It still doesn't seems to pick up the right parser. Now no matter what I get this error when running jest-runner-eslint: `SyntaxError: Unexpected token =` on class arrow function. I don't see this error in my atom editor.
