### ISSUE TITLE
Support Jest's `runInBand` option

### ISSUE THREAD

**Issue by marcins** [jest-community/jest-runner-eslint#20]
Was looking at trying to debug #19, but realised that the runner always uses a worker-farm and ignores Jest's `runInBand` option - this makes it hard to debug the runner.

Might look at adding this option first :)

**Comment by ljharb** [comment]
Seems reasonable, for testing if nothing else (if you wanted runInBand, you'd just run `eslint` :-p)

**Comment by rogeliog** [comment]
Hi! Thanks for reporting and sorry for the late response, I've been sick

@marcins That is a good point! I'll try working on it after the new years for a PR is more that welcome 😄
