### ISSUE TITLE
`cliOptions: { quiet: true }`unexpectedly reports warnings

### ISSUE THREAD

**Issue by ken-kenware** [jest-community/jest-runner-eslint#211]
I have a project where we use `{ cliOptions: { quiet: true }}` in order to not report warnings in CI.

We noticed recently that if a file had an error in it, CI would report all of the errors/warnings as errors (similar to this discussion: https://github.com/jest-community/jest-runner-eslint/issues/21). However, because I have `quiet` set to true, I would expect that ESLint should only report the errors.

I did some digging and it looks like the issue is happening because on this line, ESLint is properly filtering the events as expected:
https://github.com/jest-community/jest-runner-eslint/blob/main/src/runner/runESLint.js#L238

But then we pass the unfiltered report here: https://github.com/jest-community/jest-runner-eslint/blob/main/src/runner/runESLint.js#L249

I'm happy to submit a PR to fix!

**Comment by SimenB** [comment]
PR very much welcome 🙂

**Comment by nsunga** [comment]
@ken-kenware hello :wave:

is it possible for you to break down your file directory structure for how this runner works?

Im not sure how `cliOptions` is injected into the `jest.config.js` thats passed into `jest` -- I might be misunderstanding the current README for the setup
