### ISSUE TITLE
Document how to set this up alongside your regular jest config

### ISSUE THREAD

**Issue by Haroenv** [jest-community/jest-runner-eslint#22]
1. make two jest configs
  - one with your regular configuration
  - another one with eslint configuration
2. add `projects: ['path/to/jest-main.config.js', 'path/to/jest-eslint.config.js']` in the regular config file for Jest

Is that the recommended way?

**Comment by rogeliog** [comment]
Hi! Thanks for reporting and sorry for the late response, I've been sick

Yeah, that is a great point! I love this, PR is more than welcome 😄

**Comment by Haroenv** [comment]
So projects is the way to go? I’ll make a PR to the readme when I have access to a computer if nobody else has done it before me

**Comment by ljharb** [comment]
The "projects" array is an array of paths, according to the docs: https://facebook.github.io/jest/docs/en/configuration.html#projects-array-string - not an array of configs.

As far as I'm aware, the only solution here is "two separate jest config files".

**Comment by azz** [comment]
There's a PR to allow config objects here: https://github.com/facebook/jest/pull/5176

**Comment by keplersj** [comment]
@hph discusses this here: https://github.com/keplersj/jest-runner-prettier/issues/7#issuecomment-347366428

**Comment by macklinu** [comment]
I will open a PR today to address this.
