### ISSUE TITLE
Switch from `worker-farm` to `jest-worker`?

### ISSUE THREAD

**Issue by marcins** [jest-community/jest-runner-eslint#23]
In Jest 22 the team exposed the internal `worker-farm` equivalent, [`jest-worker`](https://github.com/facebook/jest/tree/master/packages/jest-worker). Would it be worth switching from `worker-farm` to `jest-worker` for consistency with Jest's default runner?

**Comment by rogeliog** [comment]
Yes this would be great, and even better would be to use https://github.com/rogeliog/create-jest-runner.... PR is more than welcome!

**Comment by marcins** [comment]
Ah, nice, `create-jest-runner` looks good - definitely a lot of commonality between runners. I might work on applying #20 there. We're definitely interested in using the runner for our large body of eslint checks, so am definitely intending to contribute not just raise issues 😃

**Comment by ljharb** [comment]
Raising issues is contributing! But PRs are nice :-)
