### ISSUE TITLE
Jest coverage broken when using jest-runner-eslint

### ISSUE THREAD

**Issue by evankleist** [jest-community/jest-runner-eslint#26]
Hi,

I am having a hard time getting coverage to work while using the jest-runner-eslint. While I have my jest config set to use this runner, the coverage report is all 0s. Coverage works as intended when I remove the jest-runner-eslint and let the default runner execute. I use `jest --coverage` to generate my coverage report.

**Comment by keplersj** [comment]
See https://github.com/keplersj/jest-runner-prettier/issues/7

**Comment by evankleist** [comment]
For anyone else looking at this issue, I misunderstood the way that the runners work. Any given jest runner executes for each test file. For example, the jest-runner-estlint runner executes on each file and executes eslint on that file. When you execute jest with the jest-runner-eslint, the actual tests are not executing...they are only being linted. The coverage being 0% was totally real, since no tests actually executed. In order to run tests + lint, you have to execute jest with multiple "projects" where each project is a new jest config with a different runner. My config now looks like this

**jest-default.config.js (Default runner)**
`module.exports = {
    "collectCoverageFrom": [
        "src/**/*.js"
    ],
    "moduleNameMapper": {
        "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__tests__/__mocks__/fileMock.js",
        "\\.(css|less)$": "<rootDir>/__tests__/__mocks__/styleMock.js"
    }
};
`

**jest-eslint.config.js (Eslint runner)**
`module.exports = {
    "runner": "jest-runner-eslint"
};
`

I then execute jest with `jest --coverage --projects jest-*.config.js` and end up having my tests linted, executed, and a coverage report. 

Thanks @keplersj for the link which led me to this discovery.

**Comment by keplersj** [comment]
Happy to help @evankleist!
