### ISSUE TITLE
Unknown option "cliOptions" + cache

### ISSUE THREAD

**Issue by fdubost** [jest-community/jest-runner-eslint#27]
Hi !

When I use the `cliOptions` params, I get this error :

```
Unknown option "cliOptions"  with value {"cacheLocation": ".eslintcache"} was found.
```

jest@22.1.2
jest-runner-eslint@0.4.0-0

On the other hand, cache doesn't seems to work :
- no `.eslintcache` file is created,
- when I run the command a second time, it take the same time.

Thanks for your help !

**Comment by ljharb** [comment]
What’s your full jest config?

**Comment by fdubost** [comment]
An example here :
```js
const path = require('path');
const rootDir = path.join(__dirname, '../../');

module.exports = {
  runner: 'jest-runner-eslint',
  rootDir: `${rootDir}`,
  displayName: 'lint',
  testMatch: ['<rootDir>/src/**/*.js'],
  cliOptions: {
    cacheLocation: '.eslintcache',
  },
};

```

**Comment by rogeliog** [comment]
Try putting this in your package.json

```json
"jest-runner-eslint": {
  "cliOptions": {
    "cacheLocation": ".eslintcache"
  }
}
```

**Comment by fdubost** [comment]
@rogeliog I have no error but no `.eslintcache` file is created... 😥

**Comment by dferber90** [comment]
It's not pointed out clearly in the docs that there are two configuration files.
If I read them correctly, it seems like you're mixing the config files up.

The two config files:
- `jest.config.js`
- `jest-runner-eslint.config.js`

The second one would take the `cliOptions` part.

However I couldn't get it to work with custom ESLint rules either :/

**Comment by tdeekens** [comment]
This is the current setup in a `jest-runner-eslint.config.js` file.

```
module.exports = {
  cliOptions: {
    format: 'node_modules/eslint-formatter-pretty',
    rule: [
      'import/no-unresolved: 2',
      'prettier/prettier: ["error", {"trailingComma": "es5", "singleQuote": true}]',
    ],
  },
};
```

The config seems to end up in ESLint correctly and is parsed nicely. 

```
{ cacheLocation: '.eslintcache',
     configFile: null,
     envs: [],
     extensions: [ '.js' ],
     fix: false,
     format: 'node_modules/eslint-formatter-pretty',
     globals: [],
     ignorePath: null,
     useEslintrc: true,
     ignore: true,
     allowInlineConfig: true,
     parser: null,
     parserOptions: null,
     plugins: [],
     rules:
      [ 'import/no-unresolved: 2',
        'prettier/prettier: ["error", {"trailingComma": "es5", "singleQuote": true}]' ],
     rulePaths: [] } }
```

However, the runner does not report a failing lint run whenever any of the rules does not match. Any ideas where things go wrong?

**Comment by tdeekens** [comment]
This seems to be something with the normalization of CLI options maybe. I checked what the `node_modules/.bin/eslint` receives as arguments. In case without the runner it gets

```txt
  rule:
   { 'import/no-unresolved': 2,
     'prettier/prettier': [ 'error', [Object] ] },
```

when running it with `jest-runner-eslint` the config above makes ESLint receive

```txt
  rules:
   [ 'import/no-unresolved: 2',
     'prettier/prettier: ["error", {"trailingComma": "es5", "singleQuote": true}]' 
  ],
```
