### ISSUE TITLE
latest release shows causes issues with npm outdated

### ISSUE THREAD

**Issue by szeller** [jest-community/jest-runner-eslint#29]
Would it be possible to release a `0.4.0` (or `0.5.0`) version without the trailing `-0` in the version string.  Whenever I run `npm outdated`, it tells me that latest is `0.3.0` when I'm already using `0.4.0-0`.  This is with npm version 3.10.10

**Comment by ljharb** [comment]
That's correct, because "latest" doesn't include prereleases.

When v0.4.0 is actually released, then it will become "latest".

**Comment by szeller** [comment]
Okay.  Do have an ETA for a release of v0.4.0?

**Comment by rogeliog** [comment]
Just released it.
