### ISSUE TITLE
(Ideally) Fail on Fixed Linter Errors

### ISSUE THREAD

**Issue by scott-m-sarsfield** [jest-community/jest-runner-eslint#44]
My team is using this runner to lint our app.  We have the linter called by individual developers and our CI.  

When it's an individual developer, we want to auto-fix any linter issues it comes across (we usually do this before merging).  We don't mind re-doing the linter to get all green.  (We have to do the same with ruby / rubocop.)

For the CI, though, we want it to fail / terminate, so that the imperfect code doesn't propagate through our pipeline.

Thoughts:
(1) If it could just fail whenever a linter issue is autofixed, then there's no problem.
(2) If I could have separate configurations of the runner (fix and not to fix), then that'd also address it.

**Comment by scott-m-sarsfield** [comment]
In https://github.com/jest-community/jest-runner-eslint/blob/e6ad0601675dfafdc2d9d302fdc57b7f106d4fb9/src/runESLint.js#L29

a fix, I believe, can be detected with `report.results.some( result => result.output )`

**Comment by ljharb** [comment]
I'm confused; if you want it to fail on things that are autofixed, can you not disable autofix in CI?

**Comment by ljharb** [comment]
Specifically, you can use two separate jest commands, pointing to separate configs, one for CI and one for local.

**Comment by rogeliog** [comment]
Thanks for reporting!

Let me make sure that I correctly understood the problem. You want `--fix` in development, but not in CI right?

If you happen to have your Jest config in a js file, for example `jest-eslint.config.js`, you could do the following

```js
module.exports = {
  cliOptions: {
    fix: !process.env.IS_CI
  }
}
```

**Comment by rogeliog** [comment]
As @ljharb mentioned, having two separate configs is also a good option to achieve this.

**Comment by scott-m-sarsfield** [comment]
@ljharb To be honest, I haven't had much experience with `jest` in general.  

I've set it up so that I have separate `jest` configs for unit testing + linting, but I put my `jest-runner-eslint` configuration in `package.json` and I'm unclear how I'd configure separate `jest-runner-eslint` configurations. (Since I thought `jest-runner-eslint.config.js` and `.jest-runner-eslintrc` were the only files outside of `package.json` that could be used for configuration.)

current lint jest config:
```
{
  "displayName": "lint",
  "rootDir": "../../../",
  "runner": "jest-runner-eslint",
  "testMatch": [
    // ...
  ]
}
```

However, @rogeliog 's solution seems actionable.

**Comment by scott-m-sarsfield** [comment]
Since I'm satisfied that I have a good way forward, I'm going to close the issue.

However, I'm still interested how one would go about having two separate `jest-runner-eslint` configs.

**Comment by rogeliog** [comment]
I think once https://github.com/facebook/jest/issues/4278 happens, it should eliminate the need for the separate config file.
