### ISSUE TITLE
Add Flow or TypeScript

### ISSUE THREAD

**Issue by rogeliog** [jest-community/jest-runner-eslint#50]
This repo is getting to the point where I would really like to add either Flow or TypeScript... any preference? @ljharb @SimenB I feel more comfortable with Flow but I'm happy with either.

**Comment by ljharb** [comment]
I'm not a fan of types at all, but Flow's type system seems like it'd be a lighter touch than TS's.

**Comment by SimenB** [comment]
I have no opinions on TS vs flow (I _do_ like types, though) 🙂

**Comment by SimenB** [comment]
Seeing as Jest is now in TS we should use that (if we even migrate, there's not that much code here).

**Comment by ljharb** [comment]
At this point, if there’s types, it should be TS, yes. I still prefer no types at all.

**Comment by SimenB** [comment]
Yeah, let's just close this.
