### ISSUE TITLE
Set eslint as a peer dependency

### ISSUE THREAD

**Issue by SimenB** [jest-community/jest-runner-eslint#54]
This came up in #49. Right now we depend on ESLint. Not sure exactly why TBH, but my guess is that so we have something to fall back to if we cannot find the user's version.

I think it makes more sense to add it as a peer dependency (with range on both eslint 4 and 5 probably), then we can just use `require` and not have to deal with it manually.

We can also add a peer dep range to Jest as well, especially seeing as #53 requires Jest 23

EDIT: Should resolve #41 I think

**Comment by ljharb** [comment]
A peer dep for both is definitely the proper solution.
