### ISSUE TITLE
how to use this with lint-staged?

### ISSUE THREAD

**Issue by sibelius** [jest-community/jest-runner-eslint#60]
I'm trying to use this runner on my lint-staged

the problem is when the runner does not match any file and it will return exit status 1, and it won't let lint-staged continue

any way to avoid this status 1 when no files where found?

**Comment by SimenB** [comment]
Use `--passWithNoTests`: https://jestjs.io/docs/en/cli#passwithnotests

**Comment by sibelius** [comment]
tks
