### ISSUE TITLE
Call formatter even if report.errorCount is 0

### ISSUE THREAD

**Issue by ErikBean** [jest-community/jest-runner-eslint#63]
I'm using an eslint formatter that writes the results to an output file on a build server. It needs to have these reports generated even when there are no lint errors, however, there is this in the runESLint.js file: 
```
  var report = cli.executeOnFiles([testPath]);

  if (options.cliOptions && options.cliOptions.fix) {
    CLIEngine.outputFixes(report);
  }

  var end = Date.now();

  if (report.errorCount > 0) {
    var formatter = cli.getFormatter(options.cliOptions.format);
    
    var errorMessage = formatter(CLIEngine.getErrorResults(report.results));

    return fail({
      start,
      end,
      test: { path: testPath, title: 'ESLint', errorMessage }
    });
  }
  return pass({ start, end, test: { path: testPath, title: 'ESLint' } });

```
So it will never call the formatter if there are no errors. To my knowledge, this is not how eslint currently works when run by itself. In the past it has always run the formatter regardless of whether there are errors or not. 
So I'm thinking that these might be some options:
1) Do whatever eslint does; i.e. move formatter out of if block so its always called ? 
2) Allow a config option to call formatter() prior to pass() 
3) Look at some other property on report object? (IDK, just wanted three options)

Any feedback is greatly appreciated, thank you for your time!

**Comment by SimenB** [comment]
>Do whatever eslint does

That's what we should do. Mind investigating so we're sure that's expected?

**Comment by ErikBean** [comment]
Absolutely! Thank you for your quick response. 

Here is the custom formatter we currently use, called eslint-multi-formatter:
```javascript
var assign = require('object-assign');
var sander = require('sander');
var readPkg = require('read-pkg');
var timberline = require('@nike/timberline');
var eslint = require('eslint');
var html = eslint.CLIEngine.getFormatter('html');
var json = eslint.CLIEngine.getFormatter('json');
var junit = eslint.CLIEngine.getFormatter('junit');
var stylish = eslint.CLIEngine.getFormatter('stylish');

var defaultJSONFile = 'reports/eslint.json';
var defaultHTMLFile = 'reports/eslint.html';
var defaultXMLFile = 'reports/eslint.xml';

function getSettings() {
  var pkg = {name: '@nike/eslint-multi-formatter', version: ''};  // Timberline will populate this version
  var parentPkg = {};
  try {
    parentPkg = readPkg.sync();
  } catch (err) {
    // ignore errors
  }
  const parentObj = {
    parentModule: parentPkg.name,
    parentModuleVersion: parentPkg.version
  };
  timberline.log('eslintMultiFormatter', assign({
    sourceModule: pkg.name,
    sourceModuleVersion: pkg.version
  }, parentObj));

  return parentPkg.eslintMultiFormatter || {
    jsonOutput: defaultJSONFile,
    htmlOutput: defaultHTMLFile,
    junitOutput: defaultXMLFile
  };
}

/**
 * Combines the output of the html, json, and stylish eslint formatters. The html and json outputs are written to file, stylish is returned for console output.
 * @param {object} results The results object of an eslint run.
 * @returns {string} The output of the stylish console formatters.
 */
module.exports = function processResults(results) {
  var opts = getSettings();
  opts.htmlOutput && sander.writeFile(opts.htmlOutput, html(results));
  opts.jsonOutput && sander.writeFile(opts.jsonOutput, json(results));
  opts.junitOutput && sander.writeFile(opts.junitOutput, junit(results));
  return stylish(results);
};
```
Running `eslint --color --format ./node_modules/@nike/eslint-multi-formatter/index.js site/` outputs html, json, and xml files to /reports. The JSON report looks like this for example, when there are no errors: 
```json
[{"filePath":"/Users/ebean2/Code/launch-checkout/site/.bin/fetchLoctoolTranslations.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0},{"filePath":"/Users/ebean2/Code/launch-checkout/site/analytics/client/AnalyticsClient.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0},
```
This suggests that when eslint calls our `module.exports = function processResults(results) {` it passes all the results, whereas in runESLint.js, it only passes the errors `formatter(CLIEngine.getErrorResults(report.results))`

I can dig in further to eslint to see how exactly the formatter is called, if that would be helpful. But it looks like we use it in a standard way with the --formatter flag and it receives all the results.

**Comment by ErikBean** [comment]
Looking into how eslint works a bit; this supports the idea of passing the all the results, not just the errors (see Gruntfile): 
https://github.com/eslint/eslint/blob/9c31625f19176664ef76dcf088ce50703c41c324/docs/developer-guide/working-with-custom-formatters.md#the-results-object

**Comment by SimenB** [comment]
Right. I think it makes sense to change here, then. Wanna put together a PR? 🙂

**Comment by ErikBean** [comment]
After investigating further, I'm not sure how to proceed. The report file needs to contain the results for all the files that were linted, but jest-runner-eslint is setup to do 1 file per thread, so even with --runInBand, it just overwrites the same report file a bunch of times with the results of the last file that was run. 
Seems like a naive approach would be to  write a report file for each lint run then concatenate all those arrays into 1 big one. But that's no good because it might need to write a few hundred files. What would be better is if it kept a results object in memory in the process that spawns all the child processes. I'm not sure if I can pull that off, but I can give it a shot.

**Comment by ljharb** [comment]
I’m a bit confused; can’t you use a custom reporter to sum up results?

**Comment by ErikBean** [comment]
I think what I need is to pass a formatter to eslint, I don't think a reporter will recieve the necessary info to generate the report... 
This is what the eslint.json that needs to be generated should look like (same as what gets passed to the formatter arg, if we were to run in a single thread): 
```
[{"filePath":"/Users/ebean2/Code/launch-checkout/site/.bin/fetchLoctoolTranslations.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0},{"filePath":"/Users/ebean2/Code/launch-checkout/site/analytics/client/AnalyticsClient.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0},
``` 
Whereas the reporter receives a report object that looks like this
```
{ numFailedTestSuites: 1,
  numFailedTests: 1,
  numPassedTestSuites: 196,
  numPassedTests: 284,
  numPendingTestSuites: 0,
  numPendingTests: 0,
  numRuntimeErrorTestSuites: 0,
  numTotalTestSuites: 197,
  numTotalTests: 285,
  openHandles: [],
  snapshot:
   { added: 0,
     didUpdate: false,
     failure: false,
     filesAdded: 0,
     filesRemoved: 0,
     filesUnmatched: 0,
     filesUpdated: 0,
     matched: 25,
     total: 25,
     unchecked: 0,
     uncheckedKeysByFile: [],
     unmatched: 0,
     updated: 0 },
  startTime: 1549411148863,
  success: false,
  testResults:
   [ { console: null,
       numFailingTests: 0,
       numPassingTests: 1,
       numPendingTests: 0,
       perfStats: [Object],
       snapshot: [Object],
       sourceMaps: {},
       testExecError: null,
       testFilePath: '/Users/ebean2/Code/launch-checkout/site/view/components/accordian/__tests__/content.test.js',
       testResults: [Array] },
     { console: null,
       numFailingTests: 0,
       numPassingTests: 1,
       numPendingTests: 0,
       perfStats: [Object],
       snapshot: [Object],
       sourceMaps: {},
       testExecError: null,
       testFilePath: '/Users/ebean2/Code/launch-checkout/site/view/components/verifyCVVForm/__tests__/verifyCVVForm.test.js',
       testResults: [Array] },
     { console: null,
``` 
I suppose could build the json report using a reporter, though we wouldn't get things like fixibleErrorCount and fixableWarningCount

**Comment by ErikBean** [comment]
I guess that the reporter gets this if something fails: 
```

**Comment by ErikBean** [comment]
It looks like a custom reporter will meet our needs quite well, actually. Thanks @ljharb for the suggestion! Closing this issue now since it seems like the workaround of using a custom reporter instead of a formatter is sufficient for our needs. Thanks again for your help !
