### ISSUE TITLE
Reports "NaN total"

### ISSUE THREAD

**Issue by tunnckoCore** [jest-community/jest-runner-eslint#64]
Heya!

I just notice that

```
Test Suites: 32 passed, 32 total
Tests:       32 passed, NaN total
Snapshots:   0 total
Time:        3.635s
```

I'm not sure if it was a bug before upgrading to Jest 24.

I may look later on the source code.

**Comment by SimenB** [comment]
PR: https://github.com/facebook/jest/pull/7779

**Comment by SimenB** [comment]
Will be fixed by either upgrading to `create-jest-runner@0.5.0` (PR welcome!) or wait for the next release of Jest (which hopefully is really soon)

**Comment by tunnckoCore** [comment]
I thought that too, but noticed it only when run with eslint runner.

Okey, thanks :)

**Comment by SimenB** [comment]
Belatedly, 0.7.4 had been published with a fix (although the it was also fixed in Jest some time ago)
