### ISSUE TITLE
Reuse CLIEngine instances

### ISSUE THREAD

**Issue by lencioni** [jest-community/jest-runner-eslint#87]
Right now the runner will instantiate a new CLIEngine instance for every file it runs on. 

https://github.com/jest-community/jest-runner-eslint/blob/a239b614bce32f14d4dac88209fe0d9eacfca6dc/src/runner/runESLint.js#L20-L27

I think we can make this more efficient by reusing the same instance every time. To try this out locally, I just hacked this up in my node_modules:

```diff
30a31,46
> let cachedCli;
> function getCli(config, extraOptions) {
>   if (!cachedCli) {
>     const _getESLintOptions = getESLintOptions(config),
>           baseCliOptions = _getESLintOptions.cliOptions;
> 
>     const cliOptions = _objectSpread({}, baseCliOptions, {
>       fix: getComputedFixValue(baseCliOptions)
>     }, extraOptions);
> 
>     cachedCli = { cliOptions, cli: new CLIEngine(cliOptions) };
>   }
> 
>   return cachedCli;
> }
> 
43,50c59
<   const _getESLintOptions = getESLintOptions(config),
<         baseCliOptions = _getESLintOptions.cliOptions;
< 
<   const cliOptions = _objectSpread({}, baseCliOptions, {
<     fix: getComputedFixValue(baseCliOptions)
<   }, extraOptions);
< 
<   const cli = new CLIEngine(cliOptions);
---
>   const { cli, cliOptions } = getCli(config, extraOptions);
```

My very non-scientific n=1 run on 761 files before this change:

574.30s user 86.33s system 1029% cpu 1:04.16 total

And after:

534.90s user 81.40s system 969% cpu 1:03.55 total

I'm not sure if the config or extraOptions can change between executions of this function, but it seems like they should be stable. If not, we'd want to do some smarter memoization here.

Thoughts?

**Comment by ljharb** [comment]
The problem is that the eslint config can change for every file it runs on - either from eslint config files upwards, or from any of them containing “overrides” - so it seems like there has to be a new instance for each file.

**Comment by SimenB** [comment]
I think `CLIEngine` itself does that lookup. Not sure how that mixes with mergin in the runner's specific options, though

**Comment by ljharb** [comment]
Certainly if CLIEngine handles that, and the options won't change across runs, then it seems ideal to reuse the instance - but doesn't jest's parallelization use processes, not worker threads, which means it *can't* share memory?

**Comment by SimenB** [comment]
By default it uses processes, but you can opt in to `worker_threads`: https://github.com/facebook/jest/blob/v25.3.0/packages/jest-worker/README.md#experimental-worker

**Comment by lencioni** [comment]
I just verified that CLIEngine can be reused on files in different directories while respecting nested eslintrc files.

Here's my test script:

```js
const { CLIEngine } = require('eslint');

const cli = new CLIEngine({});

const paths = ['./toplevel.js', './nested/nested.js'];
paths.forEach(path => {
  const report = cli.executeOnFiles(require.resolve(path));
  console.log(report.results);
});
```

In the two files to be linted, I put this:

```js
foo();
```

And in the eslintrc files I set this at the top level:

```json
{ "rules": { "no-undef": "error" } }
```
And this in the nested directory:
```json
{ "rules": { "no-undef": "warn" } }
```
Here's what was logged:
```js
[ { filePath: '/Users/joe_lencioni/cliengine-test/toplevel.js',
    messages: [ [Object] ],
    errorCount: 1,
    warningCount: 0,
    fixableErrorCount: 0,
    fixableWarningCount: 0,
    source: 'foo();\n' } ]
[ { filePath: '/Users/joe_lencioni/cliengine-test/nested/nested.js',
    messages: [ [Object] ],
    errorCount: 0,
    warningCount: 1,
    fixableErrorCount: 0,
    fixableWarningCount: 0,
    source: 'foo();\n' } ]
```

**Comment by lencioni** [comment]
@ljharb 
> but doesn't jest's parallelization use processes, not worker threads, which means it can't share memory?

In my hack in my node_modules directory, I added console logs for when the CLIEngine was reused and when it was instantiated. From this logging it looked like it was instantiated once for each worker, and then reused after that. I think this is a good improvement that will have increased impact as the number of files increases.

From what I can tell, this is safe. Should I open a PR?
