### ISSUE TITLE
CLI options: support --resolve-plugins-relative-to

### ISSUE THREAD

**Issue by jeysal** [jest-community/jest-runner-eslint#94]
See [ESLint docs](https://eslint.org/docs/user-guide/command-line-interface#resolve-plugins-relative-to) for the option.
This should be a rather simple change [here](https://github.com/jest-community/jest-runner-eslint/blob/4b4d99cc12cf2d870ff45d6eb4d56920d6d9359d/src/utils/normalizeConfig.js).

**Comment by ljharb** [comment]
Although the only use cases for this I'm aware of are personal configs or global installs (both deprecated), eslint supports the option, so we should too.

**Comment by jeysal** [comment]
Just curious:
I'm using it in a monorepo where the configuration is in one of the sub-packages. (The root and some other packages specify that as their `extends`.)
Without the flag, ESLint tries to resolve all the dependencies of that config from the root, which is not where they are installed. And because of PnP, this is actually being properly enforced, i.e. it fails without. The best solution to avoid having to use the flag would of course be `require.resolve`ing everything in that config, but afaik that is not possible when using things like `plugin:bla`?
@ljharb Please do correct me if I'm wrong, would love to know if there's a way to do this without the flag :sweat_smile: 
(This feature request of course remains valid regardless)

**Comment by ljharb** [comment]
I think this one boils down to subjective opinions on how to organize a mono repo; i would expect eslint to be installed at the root and invoked from a root config on all sub packages - or, to be installed in each package and a per-package lint script invoked via lerna exec or similar.

Separately, pnp breaks many things in the ecosystem, especially eslint things, which have always idiomatically relied on the structure of node_modules being present and the ability to require things that aren’t in package.json.

**Comment by jeysal** [comment]
Thing is, the config uses a lot of other presets and plugins, plus there are variants for things like React apps, not just one config. So extracting all of those configs and their dependencies from the root to a `eslint-config-something` package does make the root quite a bit cleaner. Technically, ESLint is invoked from the root, it's just that the root config is basically a reference to the subpackage - `extend: eslint-config-something`.
But yeah let's not make this issue a monorepo or ESLint config discussion :D
